Repository fsprojects/FSharp.Control.TaskSeq, pull requests merged in 2023-12, with the labels that each got.

#212 Revert "Bump actions/upload-artifact from 3 to 4"
  .github/workflows/test.yaml
Labels: dependencies, github_actions, compatibility

#209 Implement `take`, `truncate`, `skip` and `drop`
  src/FSharp.Control.TaskSeq.Test/FSharp.Control.TaskSeq.Test.fsproj
  src/FSharp.Control.TaskSeq.Test/Nunit.Extensions.fs
  src/FSharp.Control.TaskSeq.Test/TaskSeq.Skip.Tests.fs
  src/FSharp.Control.TaskSeq.Test/TaskSeq.Take.Tests.fs
  src/FSharp.Control.TaskSeq.Test/TaskSeq.TakeWhile.Tests.fs
  src/FSharp.Control.TaskSeq.Test/TestUtils.fs
  src/FSharp.Control.TaskSeq/TaskSeq.fs
  src/FSharp.Control.TaskSeq/TaskSeq.fsi
  src/FSharp.Control.TaskSeq/TaskSeqInternal.fs
Labels: topic: surface area, feature request

#216 Fix xml comments, `readme.md` and nuget's release notes and its `readme.md`
  .github/workflows/publish.yaml
  README.md
  assets/nuget-package-readme.md
  release-notes.txt
  src/FSharp.Control.TaskSeq/TaskSeq.fsi
Labels: documentation, packaging

#217 Implement `TaskSeq.where` and `TaskSeq.whereAsync`
  README.md
  assets/nuget-package-readme.md
  release-notes.txt
  src/FSharp.Control.TaskSeq.Test/TaskSeq.Filter.Tests.fs
  src/FSharp.Control.TaskSeq.Test/TestUtils.fs
  src/FSharp.Control.TaskSeq/TaskSeq.fs
  src/FSharp.Control.TaskSeq/TaskSeq.fsi
Labels: enhancement, topic: surface area

#219 Implement `TaskSeq.skipWhile`, `skipWhileAsync`, `skipWhileInclusive` and `skipWhileInclusiveAsync`
  README.md
  assets/nuget-package-readme.md
  release-notes.txt
  src/FSharp.Control.TaskSeq.Test/FSharp.Control.TaskSeq.Test.fsproj
  src/FSharp.Control.TaskSeq.Test/TaskSeq.SkipWhile.Tests.fs
  src/FSharp.Control.TaskSeq.Test/TaskSeq.TakeWhile.Tests.fs
  src/FSharp.Control.TaskSeq/TaskSeq.fs
  src/FSharp.Control.TaskSeq/TaskSeq.fsi
  src/FSharp.Control.TaskSeq/TaskSeqInternal.fs
Labels: topic: surface area, feature request

#226 Cleanup: Spelling, unused bindings
  src/FSharp.Control.TaskSeq.Test/FSharp.Control.TaskSeq.Test.fsproj
  src/FSharp.Control.TaskSeq.Test/TaskSeq.AsyncExtensions.Tests.fs
  src/FSharp.Control.TaskSeq.Test/TaskSeq.Collect.Tests.fs
  src/FSharp.Control.TaskSeq.Test/TaskSeq.Do.Tests.fs
  src/FSharp.Control.TaskSeq.Test/TaskSeq.Filter.Tests.fs
  src/FSharp.Control.TaskSeq.Test/TaskSeq.Head.Tests.fs
  src/FSharp.Control.TaskSeq.Test/TaskSeq.Last.Tests.fs
  src/FSharp.Control.TaskSeq.Test/TaskSeq.Length.Tests.fs
  src/FSharp.Control.TaskSeq.Test/TaskSeq.Let.Tests.fs
  src/FSharp.Control.TaskSeq.Test/TaskSeq.Map.Tests.fs
  src/FSharp.Control.TaskSeq.Test/TaskSeq.MaxMin.Tests.fs
  src/FSharp.Control.TaskSeq.Test/TaskSeq.Realworld.fs
  src/FSharp.Control.TaskSeq.Test/TaskSeq.Skip.Tests.fs
  src/FSharp.Control.TaskSeq.Test/TaskSeq.SkipWhile.Tests.fs
  src/FSharp.Control.TaskSeq.Test/TaskSeq.StateTransitionBug-delayed.Tests.CE.fs
  src/FSharp.Control.TaskSeq.Test/TaskSeq.StateTransitionBug.Tests.CE.fs
  src/FSharp.Control.TaskSeq.Test/TaskSeq.Take.Tests.fs
  src/FSharp.Control.TaskSeq.Test/TaskSeq.TakeWhile.Tests.fs
  src/FSharp.Control.TaskSeq.Test/TaskSeq.TaskExtensions.Tests.fs
  src/FSharp.Control.TaskSeq.Test/TaskSeq.Tests.CE.fs
  src/FSharp.Control.TaskSeq.Test/TestUtils.fs
  src/FSharp.Control.TaskSeq.Test/Xunit.Extensions.fs
  src/FSharp.Control.TaskSeq.sln.DotSettings
Labels: refactoring, cleanup, topic: unit-tests

#228 Cleanup: remove dead code, improve test coverage
  src/FSharp.Control.TaskSeq.Test/TaskSeq.Append.Tests.fs
  src/FSharp.Control.TaskSeq.Test/TaskSeq.Except.Tests.fs
  src/FSharp.Control.TaskSeq.Test/TaskSeq.Pick.Tests.fs
  src/FSharp.Control.TaskSeq.Test/TaskSeq.Realworld.fs
  src/FSharp.Control.TaskSeq.Test/TaskSeq.ToXXX.Tests.fs
Labels: refactoring, test coverage, cleanup, topic: unit-tests
